urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path

from forum.views import UserView, HomeView, ThreadView, ThreadCreateView, ThreadUpdateView, ThreadDeleteView, \
    CommentCreateView, CommentDeleteView, CommentUpdateView, CommentLikeView

urlpatterns = [
    path("admin/", admin.site.urls),

    path("login/", auth_views.login, {"template_name": "login.html"}, name="login"),
    path("logout/", auth_views.logout, name="logout"),

    path("user/<int:pk>", UserView.as_view(), name="user"),

    path("thread/<int:pk>", ThreadView.as_view(), name="thread"),
    path("thread/new", ThreadCreateView.as_view(), name="thread-new"),
    path("thread/update/<int:pk>", ThreadUpdateView.as_view(), name="thread-update"),
    path("thread/delele/<int:pk>", ThreadDeleteView.as_view(), name="thread-delete"),

    path("comment/new/<int:pk>", CommentCreateView.as_view(), name="comment-create"),
    path("comment/update/<int:pk>", CommentUpdateView.as_view(), name="comment-update"),
    path("comment/delele/<int:pk>", CommentDeleteView.as_view(), name="comment-delete"),
    path("comment/like/<int:pk>/<int:id>", CommentLikeView.as_view(), name="comment-like"),

    path("", HomeView.as_view(), name="home"),
    # url(r"^api-auth/", include("rest_framework.urls"))
]

apps/forum/models.py
from django.contrib.auth.models import User
from django.db.models import Model, ForeignKey, DateField, CharField, TextField, ManyToManyField, CASCADE


class Thread(Model):
    author = ForeignKey(User, on_delete=CASCADE)
    date = DateField(auto_now=True)
    title = CharField(max_length=255, unique=True)
    text = TextField()

    def __str__(self):
        return self.title


class Comment(Model):
    thread = ForeignKey(Thread, on_delete=CASCADE)
    author = ForeignKey(User, on_delete=CASCADE)
    date = DateField(auto_now=True)
    text = TextField()
    like = ManyToManyField(User, related_name="userlike", blank=True)

    def __str__(self):
        return str(self.thread) + " / " + str(self.author)

apps/forum/forms.py
from django.forms import ModelForm

from .models import Comment


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ("text",)

apps/forum/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Count
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView, View
from rest_framework.exceptions import PermissionDenied

from .forms import CommentForm
from .models import Comment, Thread


# "default" view showing list of @Thread
class HomeView(ListView):
    model = Thread
    template_name = "home.html"
    paginate_by = 25
    ordering = ["-id"]


# displays all @Thread created/commented on by specific @User
class UserView(DetailView):
    model = User
    template_name = "user.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # get list of @Thread ids @User commented on
        thread_ids = set(Comment.objects.filter(author=self.kwargs["pk"]).values_list(flat=True))

        context["thread_user_list"] = Thread.objects.filter(author=self.kwargs["pk"]).order_by("id")
        context["thread_comment_list"] = Thread.objects.filter(author__in=thread_ids).order_by("id")
        context["user"] = self.request.user
        return context


# @Thread-oriented views:


class ThreadView(DetailView):
    model = Thread
    template_name = "thread.html"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["comment_list"] = Comment.objects.filter(thread=context["thread"]).annotate(
            count=Count("like")).order_by("id")
        context["comment_form"] = CommentForm
        return context


class ThreadCreateView(LoginRequiredMixin, CreateView):
    model = Thread
    template_name = "thread_form.html"
    fields = ["title", "text"]

    def get_success_url(self):
        return reverse_lazy("thread", kwargs={"pk": self.object.id})

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super(ThreadCreateView, self).form_valid(form)


class ThreadUpdateView(LoginRequiredMixin, UpdateView):
    model = Thread
    template_name = "thread_form.html"
    fields = ["text"]

    def form_valid(self, form):
        if self.request.user != self.object.author:
            raise PermissionDenied("You can't edit others ppl threads!")
        return super(ThreadUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("thread", kwargs={"pk": self.object.id})


class ThreadDeleteView(LoginRequiredMixin, DeleteView):
    model = Thread
    template_name = "thread_delete.html"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user != self.object.author:
            raise PermissionDenied("You can't delete others ppl threads!")
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy("home")


# @Comment-oriented views:


class CommentCreateView(LoginRequiredMixin, CreateView):
    model = Comment
    fields = ["text"]

    # disable GET request
    def get(self, request, *args, **kwargs):
        return redirect("thread", pk=self.kwargs["pk"])

    def get_success_url(self):
        return reverse_lazy("thread", kwargs={"pk": self.kwargs["pk"]})

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.thread = Thread.objects.get(id=self.kwargs["pk"])
        return super(CommentCreateView, self).form_valid(form)


class CommentUpdateView(UpdateView):
    model = Comment
    template_name = "comment_form.html"
    fields = ["text"]

    def form_valid(self, form):
        if self.request.user != self.object.author:
            raise PermissionDenied("You can't edit others ppl comments!")
        return super(CommentUpdateView, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy("thread", kwargs={"pk": self.object.thread.id})


class CommentDeleteView(DeleteView):
    model = Comment
    template_name = "comment_delete.html"

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        if self.request.user != self.object.author:
            raise PermissionDenied("You can't delete others ppl comments!")
        self.object.delete()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse_lazy("thread", kwargs={"pk": self.object.thread.id})


class CommentLikeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        obj = Comment.objects.get(id=self.kwargs["id"])
        if obj.like.filter(id=self.request.user.id).exists():
            obj.like.remove(self.request.user)
        else:
            obj.like.add(self.request.user)
        obj.save()
        return redirect("thread", pk=self.kwargs["pk"])

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>forum | {% block title %}{% endblock title %}</title>
</head>
<body>
<header>
    <h1>forum</h1>
    <p>
        {% if user.is_authenticated %}
            Logged as <a href="{% url "user" user.id %}">{{ user }}</a> / <a href="{% url "logout" %}">Log out</a>
        {% else %}
            You are not logged in. <a href="{% url "login" %}">Log in</a>
        {% endif %}
    </p>
    <nav>
        {% block nav %}
        {% endblock nav %}
    </nav>
</header>
<main>
    {% block content %}
    {% endblock content %}
</main>
</body>
</html>

templates/comment_delete.html
{% extends "base.html" %}

{% block title %}Delete comment on {{ object.thread.title }}{% endblock title %}

{% block nav %}
    <a href="{% url "thread" object.thread.id %}">Back to thread</a>
{% endblock nav %}

{% block content %}
    <h2>Delete comment on <i>{{ object.thread.title }}?</i></h2>
    <p>Are you sure about deleting thread <strong>{{ object.title }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Delete</button>
        <a href="{% url "thread" object.thread.id %}">Cancel</a>
    </form>
{% endblock content %}

templates/comment_form.html
{% extends "base.html" %}

{% block title %}Update your comment{% endblock title %}

{% block nav %}
    <a href="{% url "thread" object.thread.id %}">Back to thread</a>
{% endblock nav %}

{% block content %}
    <h2>Update your comment on {{ object.thread.title }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
    </form>
{% endblock content %}

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock title %}

{% block nav %}
    {% if user.is_authenticated %}
        <a href="{% url "thread-new" %}">Start new thread</a>
    {% endif %}
{% endblock nav %}

{% block content %}
    <h2>Threads</h2>
    <ul>
        {% for thread in thread_list %}
            <li><a href="{% url "thread" thread.id %}">{{ thread.title }}</a> by <a
                    href="{% url "user" thread.author.id %}">{{ thread.author }}</a> on {{ thread.date }}</li>
        {% empty %}
            r/Wooosh
        {% endfor %}
    </ul>
{% endblock content %}

templates/login.html
{% extends "base.html" %}

{% block title %}Login{% endblock title %}

{% block content %}
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
{% endblock content %}

templates/thread.html
{% extends "base.html" %}

{% block title %}Thread: {{ object.title }}{% endblock title %}

{% block nav %}
    <a href="{% url "home" %}">Back to home</a>
    {% if user.is_authenticated and user == thread.author %}
        |
        <a href="{% url "thread-update" thread.id %}">Edit</a>
        <a href="{% url "thread-delete" thread.id %}">Delete</a>
    {% endif %}
{% endblock nav %}

{% block content %}
    <h2>{{ object.title }}</h2>
    <p><i>Created by <a href="{% url "user" object.author.id %}">{{ object.author }}</a> on {{ object.date }}.</i></p>
    <p>{{ object.text }}</p>
    <h3>Comments</h3>
    <ul>
        {% for comment in comment_list %}
            <li>[{{ comment.date }}] <strong><a
                    href="{% url "user" comment.author.id %}">{{ comment.author }}</a></strong>: {{ comment.text }}
                <i>{{ comment.count }}</i>
                {% if user.is_authenticated %}
                    | <a href="{% url 'comment-like' object.id comment.id %}">Like</a>
                    {% if user == comment.author %}
                        <a href="{% url "comment-update" comment.id %}">Edit</a>
                        <a href="{% url "comment-delete" comment.id %}">Delete</a>
                    {% endif %}
                {% endif %}</li>
        {% empty %}
            r/Wooosh
        {% endfor %}
    </ul>
    <h3>Post comment:</h3>
    <form method="post" action="{% url 'comment-create' object.id %}">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <button>Submit</button>
    </form>
{% endblock content %}

templates/thread_delete.html
{% extends "base.html" %}

{% block title %}{{ object.title }} - Delete{% endblock title %}

{% block nav %}
    <a href="{% url "home" %}">Back to home</a>
{% endblock nav %}

{% block content %}
    <h2>Delete <i>{{ object.title }}?</i></h2>
    <p>Are you sure about deleting thread <strong>{{ object.title }}</strong>?</p>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Delete</button>
        <a href="{% url "thread" object.id %}">Cancel</a>
    </form>
{% endblock content %}

templates/thread_form.html
{% extends "base.html" %}

{% block title %}
    {% if not object.title %}
        Start new thread
    {% else %}
        {{ object.title }} - Edit
    {% endif %}
{% endblock title %}

{% block nav %}
    <a href="{% url "home" %}">Back to home</a>
{% endblock nav %}

{% block content %}
    <h2>
        {% if not object.title %}
            Start new thread
        {% else %}
            Edit <i>{{ object.title }}</i>
        {% endif %}
    </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit</button>
        <a href="{% url "home" %}">Cancel</a>
    </form>
{% endblock content %}

templates/user.html
{% extends "base.html" %}

{% block title %}User: {{ object }}{% endblock title %}

{% block nav %}
    <a href="{% url "home" %}">Back to home</a>
{% endblock nav %}

{% block content %}
    <h2>{{ object }}</h2>
    <h3>Created threads</h3>
    <ul>
        {% for thread in thread_user_list %}
            <li><a href="{% url "thread" thread.id %}">{{ thread.title }}</a> on {{ thread.date }}</li>
        {% empty %}
            r/Wooosh
        {% endfor %}
    </ul>
    <h3>Threads commented on</h3>
    <ul>
        {% for thread in thread_comment_list %}
            <li><a href="{% url "thread" thread.id %}">{{ thread.title }}</a> by <a
                    href="{% url "user" thread.author.id %}">{{ thread.author }}</a> on {{ thread.date }}</li>
        {% empty %}
            r/Wooosh
        {% endfor %}
    </ul>
{% endblock content %}